# Generated by Django 4.2.1 on 2023-05-31 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_warranty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="product",
            name="warranty",
        ),
    ]
