# Generated by Django 4.2.1 on 2023-05-31 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_remove_product_brand_remove_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.brand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.seller",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty",
            field=models.ForeignKey(
                blank=True,
                default=2324,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.warranty",
            ),
            preserve_default=False,
        ),
    ]
